# SwiftLint configuration file
# Refer to: https://github.com/realm/SwiftLint/#configuration

disabled_rules: # rule identifiers to exclude from running
  - line_length
  - nesting
  - trailing_whitespace

opt_in_rules: # some rules are only opt-in
  - empty_count
  - empty_string
  - first_where
  - force_unwrapping
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - function_default_parameter_at_end
  - weak_delegate
  - file_length

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Weather/Resources/R.generated.swift

identifier_name:
  excluded: # excluded via string array
    - uv
    - id
